### PR TITLE
New Translation and Deployment system.

### PR DESCRIPTION
**Pull request by martinheidegger**
We have (had?) two bigger issues with the website: 

1. is SEO: all the translations are only shown on the website, google can not properly index them
2. We have some build scripts that every new chapter forgets to run. (I am a little tired of pointing it out to people)

I took a night and created a build script that does pretty much what the current scripts do but instead of running the translation in the browser I create a deploy script that can be connected to codeship and be used for deployment. I set it up for testruns at http://nodeschooltest.github.io/ and https://github.com/nodeschooltest/nodeschooltest.github.io

Do you think its a bad idea to use this in the site from now on?
Particularily: @maxogden 

Disclaimer: There are a few tasks open
- [x] JavaScript redirect for first time users
- [x] Update the contribution documentation

### CODE REVIEW

**Comment by maxogden** [comment]
@martinheidegger i'm not familiar with codeship, would using that for deploys make it so we could only deploy the site if codeship is working? e.g. is there still a way to deploy without relying on a third party service (other than github of course)

**Comment by martinheidegger** [comment]
Codeship basically is only a git hook (like travis) that runs `npm run deploy` after every deploy. So you can run the deployment in a regular shell as well.

**Comment by martinheidegger** [comment]
This is the configuration I had to setup at codeship:

```
nvm install 0.10.25
nvm use 0.10.25
npm i
git config --global user.email "martin.heidegger@gmail.com"
git config --global user.name "Martin Heidegger"
npm run deploy
```

Also I need to set a `GITHUB_USER` and `GITHUB_ACCESS_TOKEN` at the moment.

**Comment by maxogden** [comment]
@martinheidegger ah cool, I see! as long as theres no central-point-of-failure and things are documented such that if you go off into the Japanese forest for 6 months to escape the internet we can still deploy without you then I am +1 :)

**Comment by SomeoneWeird** [comment]
+1

**Comment by martinheidegger** [comment]
Okay system changed!

**Pull request closed without merging**
