### PR TITLE
More translate to Bahasa

### PR DESCRIPTION
**Pull request by deriidf**
more effective and translating according to KBBI

### CODE REVIEW

**Comment by fforres** [comment]
Not really my language :/ 
@deriidf can you tag someone that can help us double check?

**Comment by deriidf** [comment]
You can check on kbbi.web.id (Kamus Besar Bahasa Indonesia/Large Indonesia Dictionary)
try search 'silakan' and 'silahkan', there is now 'silahkan' word. and 'Event' translate to Indonesia is 'Acara'

**Comment by fforres** [comment]
Awesome, LGTM

**Comment by riyadhalnur** [comment]
Thank you! Merged 🚀 I had @nerezza07 helped me review the translation

**Pull request merged**
