### PR TITLE
Update version of jsdom and posix

### PR DESCRIPTION
**Pull request by kohei-takata**
refs #419

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
Tested?

**Comment by kohei-takata** [comment]
I checked that server runs correctly by using `npm run start` command.
I use node v4.2.2 and npm v3.3.12.

**Comment by riyadhalnur** [comment]
on Windows 10 i presume?

**Comment by kohei-takata** [comment]
No, I use Mac OSX.

**Comment by riyadhalnur** [comment]
We need to test on a Windows machine. I'll test it on my Windows 10 machine tonight if possible

**Comment by kohei-takata** [comment]
I see. Thanks.

**Comment by gutierri** [comment]
Something?

**Comment by martinheidegger** [comment]
Tested on windows and it didn't work, submitted #454 which is built on this issue. I hope you don't mind me closing this PR. If you do please reopen.

**Pull request closed without merging**
