### PR TITLE
add turkish translation

### PR DESCRIPTION
**Pull request by tetsuo**

### CODE REVIEW

**Comment by tetsuo** [comment]
i think this is mergeable now @maxogden @martinheidegger any turkish-speaking friends you have out there? :) need some proofreading or smth before merging? do u trust me :hatching_chick:

**Comment by martinheidegger** [comment]
We will find more cooperators once its published.

**Comment by tetsuo** [comment]
cool, that was fast. @martinheidegger  can i have a badge on my gh profile btw :family:

**Comment by martinheidegger** [comment]
badge?

**Comment by tetsuo** [comment]
yep!

**Comment by martinheidegger** [comment]
Will you open a chapter? :wink:  I added you to the organisation anyways. https://github.com/nodeschool/organizers/issues/28

**Comment by tetsuo** [comment]
yayyy tx :smiley_cat:  yup gonna organize an event in antalya hopefully on international day

**Comment by martinheidegger** [comment]
@tetsuo I usually setup an event site at least 3 weeks before an event, gotta hurry for international day by my calculation :wink:

**Pull request merged**
