### PR TITLE
Adding new chapter and logo - NodeSchool Silesia.

### PR DESCRIPTION
**Pull request by afronski**

### CODE REVIEW

**Comment by afronski** [comment]
@martinheidegger New chapter should be visible on the [main list](http://nodeschool.io/chapters.html) immediately? Should I run `npm build`?

**Comment by afronski** [comment]
@martinheidegger Did you run `npm run deploy` or we missed something? ;)

**Comment by martinheidegger** [comment]
@afronski oh! sorry for that, its been a while since I published the site :smile: . Should be okay now, right?

**Comment by afronski** [comment]
@martinheidegger Yup, it's fine now. Anyway thanks :+1:.

**Pull request merged**
