### PR TITLE
Add google analytics tracking for workshopper links clicks

### PR DESCRIPTION
**Pull request by sudodoki**
As discussed in #337.
Have some doubts whether this code is good enough.
It's a bit fragile, because:
1) it relies on id & class selectors for containers, as well as layout to be the same (with first `.third` item to contain info only, and not track those link clicks [although we could totally track how many people are following issues link when willing to ask a question])
2) it relies on href to provide workshopperId (which would be the reponame, given all links are to github)
Would love to hear feedback and modify code accordingly.

### CODE REVIEW

**Comment by maxogden** [comment]
@sudodoki hmmm maybe we should just add a new class to the markup e.g. `.workshop-link` that is used specifically for tracking these

**Comment by sudodoki** [comment]
@maxogden yep, definetely was thinking about something like this. Only drawback is markup getting waaaaay to verbose than it should be. I would use `js-workshop-link` to denote it's not appearance class but something used in the scripts.

**Comment by martinheidegger** [comment]
@maxogden @sudodoki Maybe we should use template tags and convert the html file to handlebars? (I also think that the description texts (including translation!) should be moved to the respective tutorials and fetched while building.

**Comment by sudodoki** [comment]
@martinheidegger pretty sure previous discussion regarding site improvements should avoid adding build steps. Not sure @maxogden feels the same way still.

**Comment by martinheidegger** [comment]
@sudodoki previous discussions didn't have a automatic deploy system in place.

**Comment by martinheidegger** [comment]
Will merge the PR now. Please fix it later.

**Comment by sudodoki** [comment]
>(which we have since recently)

Oh, I missed that, where's PR/issue with discussion?

**Comment by martinheidegger** [comment]
https://github.com/nodeschool/nodeschool.github.io/pull/330

**Pull request merged**
