### PR TITLE
Extracting footers to file and injecting during build-html script

### PR DESCRIPTION
**Pull request by interannette**
While working on #306 and #587 I realized that the footer is duplicated across all the html files. When I add the license link to the footer for #587, the license link was only added to index.html. Rather manually update the footer across all the html files, I decided to try to inject the footer as part of the build-html.js script.

Having read CONTRIBUTING.md, I realize the goal is to keep things simple. While using the build script to insert the header is less simple than having the footer duplicated, I think it's worth the extra complexity. But, if that's not the consensus, I can manually update the remaining footers to be consistent with the index.html changes made in #587 

I tested this by running "npm start" and confirmed the footer appeared. I did notice that this breaks the translation of the footer. I believe I can fix that, but I'd like to get buy in for this approach before investing more time in it.

### CODE REVIEW

**Comment by riyadhalnur** [comment]
It makes sense to me. The injection code is not complex and doesn't add much overhead. I'm all for this going forward. Easier to maintain during any future updates. Thank you @interannette 😃

**Comment by fforres** [comment]
So cooll!! LGTM!! 😄

**Comment by interannette** [comment]
I finally got time to look at this again and have fixed the issue with translation. The footer is now being injected AND translated.

**Comment by riyadhalnur** [comment]
Thank you again @interannette! Merged 🚀

**Pull request merged**
