### PR TITLE
Add learnyoubash workshopper

### PR DESCRIPTION
**Pull request by denysdovhan**
I've made a workshopper about using the terminal and Bash. Check out [learnyoubash](https://github.com/denysdovhan/learnyoubash)!

image

### CODE REVIEW

**Comment by RichardLitt** [comment]
I think this is pretty awesome. But I'm not sure if there is enough justification; why is this relevant to node? Can you include a bit more context for that?

**Comment by robbiethegeek** [comment]
I think there are plenty of workshoppers at this point that aren't node
specific.

**Comment by denysdovhan** [comment]
Personally, I can't image my working process without the terminal. And I'm completely sure you too. At the same time, I often saw the people who was confused by using of terminal. I'm trying to solve this problem.

**Comment by RichardLitt** [comment]
Cool. Agreed, just want to surface that. I think this should be added.

**Comment by denysdovhan** [comment]
This workshopper based on my [bash-handbook](https://github.com/denysdovhan/bash-handbook), but it's not only about Bash. In exercises the users will learn about basic commands, such as: `cd`, `ls`, `mkdir`, `touch`, `alias`, `pwd`, `chown`, `chmod`, etc.

**Comment by martinheidegger** [comment]
@RichardLitt likes it and I like it so I merged it.

**Comment by RichardLitt** [comment]
Woot. Thanks, @denysdovhan

**Pull request merged**
