### PR TITLE
[Done ] Arabic Translation ..

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
I liked your idea ( NODESCHOOL ) .. So I love publishing it within the Arab community so I translated the site into Arabic and I will strive to update it and improve translation always .. 
Thank you

### CODE REVIEW

**Comment by 3imed-jaberi** [comment]
@riyadhalnur  Bro , 
Is there a problem in my translation 🤔 !!

**Comment by riyadhalnur** [comment]
@3imed-jaberi not at all but since I don't know Arabic, the translation should be reviewed by someone who does

**Comment by 3imed-jaberi** [comment]
> @3imed-jaberi not at all but since I don't know Arabic, the translation should be reviewed by someone who does
@riyadhalnur If you don't have anyone who is fluent in the Arabic language, I can join the org. and be the reference or add a group of my developer friends with me and we will be the Arab reference ...

**Comment by riyadhalnur** [comment]
@3imed-jaberi that would be great if you could ask someone you know to review this. they don't need to be part of the org to review

**Comment by 3imed-jaberi** [comment]
> @3imed-jaberi that would be great if you could ask someone you know to review this. they don't need to be part of the org to review

@riyadhalnur  ok bro , i will ask someone ..

**Comment by chaoukibenfredj** [comment]
I reviewed the translation and it's perfect. Good Job @3imed-jaberi

**Comment by riyadhalnur** [comment]
Thank you! Merged 🚀

**Pull request merged**
