### PR TITLE
Fix event calendar

### LINKED ISSUE #225: Wrong days of the week in events page
In the [events page](http://nodeschool.io/events.html) the days of the week for FEB 2015 and MAR 2015 are wrong, the 1st is shown as Monday (when Feb 1st was on a Sunday and Mar 1st will be on a Wednesday). See below.

calendar-mar-2015

### PR DESCRIPTION
**Pull request by muan**
This should fix #225.

`table.js` was pretty out of date, this syncs the code with head of https://github.com/jlord/sheetsee-calendar, with [my latest changes](https://github.com/jlord/sheetsee-calendar/compare/5438796350e7d52def89a839f29a12c4963056ee...954d4a86b703244d62b7dbe31ba034a7cb1341e9) that are supposed to address the start date issue.

I've also made some slight CSS changes so it looks less crooked. 

There's an event in 1999, which I assume is incorrect data, maybe someone who has admin access to the spreadsheet can edit it?

**Local env screenshot**

image

cc @maxogden @jlord

### CODE REVIEW

**Comment by maxogden** [comment]
giphy

**Comment by jlord** [comment]
When I first saw the email for this PR I was like HECK YES THIS PERSON INCLUDED A SCREENSHOT. Then I saw that it was you, @muan, who is wise and good, and thus I still have to hold out hope for general population lololol :grin:

**Comment by jlord** [comment]
- [x] removed spammy 1999 entry

**Comment by alexfernandez** [comment]
Hey, hold up your hopes! _This_ person included a screenshot in #225, and I guess I'm general population enough :P

**Pull request merged**
