### PR TITLE
Add IEM Kolkata Chapter file

### PR DESCRIPTION
**Pull request by koustuvsinha**
Add IEM Kolkata Chapter file : https://github.com/nodeschool/iem-kolkata

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
```
If you've added a new local chapter, don't forget to run npm build before submitting your pull request so all the appropriate json files are updated.
```

:+1:

**Comment by fmoliveira** [comment]
@SomeoneWeird , isn't npm build ran automatically through Continuous Integration with CodeShip?

I've merged a few pull requests to add chapters [such as this](https://github.com/nodeschool/nodeschool.github.io/pull/393/files) and a few seconds later the chapter was online at the website.

**Comment by SomeoneWeird** [comment]
Quite possibly. I wasn't aware we set up codeship for this repo. I'll update the readme.

**Comment by SomeoneWeird** [comment]
https://github.com/nodeschool/nodeschool.github.io/commit/40526f0bb77a4d686cfcab7cc4536fb876cc55a2 seemed to work

**Comment by fmoliveira** [comment]
:smiley:  :+1:

**Comment by koustuvsinha** [comment]
@SomeoneWeird actually i saw some PR's with only the json file added, thus went on to do that!

**Pull request merged**
