### PR TITLE
Add nodeschool fort-worth chapter+hex

### PR DESCRIPTION
**Pull request by hodorswit**
Let me know if anything needs to be tweaked.

CC @beneventofrank and @givingforwardmegan

### CODE REVIEW

**Comment by riyadhalnur** [comment]
Any update on this?

**Comment by hodorswit** [comment]
@riyadhalnur This is ready to be merged provided that I have not violated any conventions or contributor guidelines.

**Comment by riyadhalnur** [comment]
LGTM 👍

**Comment by riyadhalnur** [comment]
Thank you! Merged 🚀

**Pull request merged**
