### PR TITLE
new international picture

### PR DESCRIPTION
**Pull request by oleharland**

### CODE REVIEW

**Comment by finnp** [comment]
:+1:

**Comment by martinheidegger** [comment]
Can you make the text translatable?

**Comment by oleharland** [comment]
it is now a big picture so you have to code it when you want to do that. Or do you swap the pictures for the languages?

**Comment by finnp** [comment]
@oleharland Could you add the background image of the banner? (What's the source for that by the way?) Then we could add the logo and the text with html/css on top so it would be easy to translate it. Also we could make it responsive this way.

**Comment by oleharland** [comment]
@finnp at the moment its a composing from differnt pictures out of google but if we upload it seperatly we should do a bit more retouching to avoid copyright violation.

i will do it in the next days and put up here the assets and then a psd that you guys can work with it.

**Comment by finnp** [comment]
@oleharland Okay great. If your picture is from NASA it's okay to use it, like this one: http://visibleearth.nasa.gov/view.php?id=57723

**Comment by finnp** [comment]
@martinheidegger I just made the banner translatable in case you want to add a translation.

**Pull request merged**
