### PR TITLE
Fixed LA hex on the hexdex page.

### PR DESCRIPTION
**Pull request by kmckee**
Solves #394

### CODE REVIEW

**Comment by fmoliveira** [comment]
I've edited your message body to include the related issue number, so it'll be automatically closed when the pull request is accepted.

**Comment by kmckee** [comment]
Thanks :)

**Comment by fmoliveira** [comment]
You're welcome! ;)

**Comment by fmoliveira** [comment]
Looks good to me. I've tested it and it's safe to merge.

**Comment by fmoliveira** [comment]
The automatic closing didn't work because I've included the wrong word, it should be "fixes" instead of "solves" as per https://github.com/blog/1506-closing-issues-via-pull-requests .

I'll close that manually.

**Comment by fmoliveira** [comment]
Thanks @kmckee ! ;)

**Pull request merged**
