### PR TITLE
[WIP] Create Ukrainian translation

### PR DESCRIPTION
**Pull request by sudodoki**

### CODE REVIEW

**Comment by ghaiklor** [comment]
I just have updated localization. I think we can merge it. @sudodoki, what you think?

**Comment by sudodoki** [comment]
It's too many commit s for some reason. Maybe, it would be better to remove merge and instead rebase on master?

**Comment by ghaiklor** [comment]
@sudodoki, I made rebase from master to this branch. I can rebase to master and update pull request.

**Comment by sudodoki** [comment]
Closed in favour of #189.
Thanks for support @finnp! :bow: 
Really glad there're more people getting involved w/ nodeschool in Ukraine.

**Pull request closed without merging**
