### PR TITLE
Added learn-sass to elective workshoppers

### PR DESCRIPTION
**Pull request by claudiopro**
Hi, I'm proposing to add the [learn-sass](https://www.npmjs.com/package/learn-sass) workshopper adventure to the elective workshoppers. I also added the Spanish translation for the caption.

### CODE REVIEW

**Comment by iancrowther** [comment]
great - im a less guy and would like to play with sass

**Comment by claudiopro** [comment]
I took the liberty to add an Italian localization, feel free to reject if you'd rather have the translation in a separate PR.

**Comment by iancrowther** [comment]
What's the merge policy? 2 confirms?

**Comment by SomeoneWeird** [comment]
:ok_hand:

**Comment by claudiopro** [comment]
Awesome, thanks!

**Pull request merged**
