### PR TITLE
Adding information from node school wisconsin.

### PR DESCRIPTION
**Pull request by blakehall**
We held the first Nodeschool Wisconsin in conjunction with BarCamp Green Bay in November 2014. As we start planning our next event, it would be nice to be listed along with the other chapters on the main site.

cc/ @zo0o0ot

### CODE REVIEW

**Comment by adamniedzielski** [comment]
Please run ```npm run build``` to regenerate ```list.json``` file.

I guess this should be documented in ```README.md```

**Comment by blakehall** [comment]
Thanks for the pointer @adamniedzielski. I went ahead and added some (limited) initial documentation about `npm build` to the README as well.

**Comment by zo0o0ot** [comment]
It would be nice to have our Nodeschool Wisconsin hex in the hex list too.  It's been on my todo list to add it.  I seem to recall that there's a list of all of them somewhere, but it's completely eluding me at the moment.

**Comment by zo0o0ot** [comment]
Also, I'm not sure it's worth putting on the main nodeschool site, but I did post an event wrap-up and post mortem for the first nodeschool Wisconsin event on my blog:  http://zootlinux.blogspot.com/2014/12/nodeschool-wisconsin-premiere-event.html

**Comment by julianduque** [comment]
@blakehall can you rebase with master?

**Comment by blakehall** [comment]
@julianduque I think that should do it?

**Comment by julianduque** [comment]
Thanks!

**Pull request merged**
