### PR TITLE
add missing logos to hexdex

### PR DESCRIPTION
**Pull request by a0viedo**
Add missing @nodeschool/costarica, @nodeschool/berlin, @nodeschool/italy and @nodeschool/hermosillo logos.

I think there are some missing yet, like @nodeschool/zagreb, @nodeschool/belgrade and @nodeschool/tacoma.

### CODE REVIEW

**Comment by riyadhalnur** [comment]
Thank you! Merged 🚀

**Comment by gaboesquivel** [comment]
thanks!

**Comment by usmantahirr** [comment]
Lahore Chapter logo is missing as well. How can I add it to repository?

**Comment by a0viedo** [comment]
@usmantahirr same thing I did here! Clone the repo, add the missing logo to the `images` directory, change the "hexdex.html" file with a new element to display the added logo, commit and push to your fork and submit a new pull request.

If you get stuck in any step let me know.

**Pull request merged**
