### PR TITLE
moving ga token into header to comply with google site verification

### PR DESCRIPTION
**Pull request by iancrowther**
see attached screenshot

screen shot 2016-03-19 at 00 18 52

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
Cool :)

Is it possible to invite people to view the GA for that? (me? :P)

**Comment by iancrowther** [comment]
I don't have the power cap'n..

cc' @maxogden

**Comment by martinheidegger** [comment]
@SomeoneWeird It seems to me that  "authorization" requests should be managed through https://github.com/nodeschool/organizers/issues

**Comment by SomeoneWeird** [comment]
Sure, but there wasn't much point opening another issue when I could have killed two birds with one stone in this issue :)

**Pull request merged**
