### PR TITLE
Create fa.json

### PR DESCRIPTION
**Pull request by mrfarhadir**
Adding Persian(Farsi) language

### CODE REVIEW

**Comment by fforres** [comment]
So cool @mrfarhadir 
I personally don't know any Persian(Farsi).
Would you be willing to get someone else that can help up with the review process ??

**Comment by ZJaf** [comment]
Hey @mrfarhadir, I speak Farsi(Persian) and I love to help with this PR. How would you like me to contribute?

**Comment by mrfarhadir** [comment]
@ZJaf Thanks for your contribute , we could divide it into two part and start to translate then merge it 
could u tell me any Id for being able to talk or chat  in detail ?

**Comment by ZJaf** [comment]
Sure, find me on hangout: haniejafarii@gmail.com

**Pull request merged**
