### PR TITLE
Add how-to-npm to workshoppers

### PR DESCRIPTION
**Pull request by tapsboy**
how-to-npm learning module is written by the creator of npm, Isaac. I am just opening a PR to add it to 'Electives'

### CODE REVIEW

**Comment by martinheidegger** [comment]
Is @isaacs okay with it?

**Comment by watson** [comment]
@martinheidegger any reason why he shouldn't?

**Comment by maxogden** [comment]
it hit 1.0.0 yesterday (https://github.com/npm/how-to-npm/commits/master), I say ship it!

**Comment by martinheidegger** [comment]
@watson Basic curtesy to ask.

**Comment by watson** [comment]
@martinheidegger guess you are right - was just thinking why you wouldn't want someone to link to your module ;) But it's always nice to ask

**Comment by maxogden** [comment]
they did the workshop today at nodesummit, so im gonna merge :)

**Comment by isaacs** [comment]
Yes please. Thanks everyone. Went pretty ok.

**Comment by tapsboy** [comment]
Thanks @maxogden for merging and moving to core. Thanks for the module @isaacs; fills an important gap for node beginners

**Pull request merged**
