### PR TITLE
Add perfschool workshopper to electives

### PR DESCRIPTION
**Pull request by bevacqua**
See https://github.com/bevacqua/perfschool

### CODE REVIEW

**Comment by martinheidegger** [comment]
The title is slightly misleading. It doesn't focus on node.js performance but on frontend performance if I am not mistaken?!

**Comment by bevacqua** [comment]
How is the name misleading? There's a screenshot with a full list of exercises at the top of the README..

It's not like I mention Node.js anywhere.

**Comment by martinheidegger** [comment]
`NodeSchool` <- mentions node ;)

**Comment by bevacqua** [comment]
Well, it's a workshopper I'll be using in NodeSchool, so sue me! Haha. The description also has `#perfmatters` which is usually associated with web performance

**Comment by martinheidegger** [comment]
@bevacqua Don't get me wrong: I like the workshopper. I just think it should mention somewhere that it is dealing with frontend issues (there are backend issues as well, you know)

**Comment by bevacqua** [comment]
That's fair enough. Would updating the tagline in the pull request put you at ease?

**Comment by martinheidegger** [comment]
sure

**Comment by bevacqua** [comment]
How about just adding `web`?

> Find your way through the web performance optimization maze!

**Comment by martinheidegger** [comment]
Frontend?

**Comment by bevacqua** [comment]
It's more than just frontend, you spend the day in the terminal and use
stuff like gm, pagespeed, phantomjs, etc

On Wednesday, May 13, 2015, Martin Heidegger <notifications@github.com>
wrote:

> Frontend?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/nodeschool.github.io/pull/329#issuecomment-101784301>
> .
>


-- 


github <https://github.com/bevacqua> · blog <http://blog.ponyfoo.com/> ·
twitter <https://twitter.com/nzgb> · book <http://bevacqua.io/buildfirst> ·
career <http://careers.stackoverflow.com/bevacqua> ·about
<http://bevacqua.io/>

**Comment by martinheidegger** [comment]
To me this is all frontend :smile:  after all it doesn't contain any DNS improvement things or database strategies, memory management or session management that would concern servers. If you are not happy with fronend - i can go with web ....

**Comment by bevacqua** [comment]
There. I promise I'll add more info about changes in HTTP/2 and we have a deal :package:?

**Comment by martinheidegger** [comment]
http/2 still 50% a frontend issue :wink: but i merged it.

**Comment by bevacqua** [comment]
That's what the *web* runs on top of, not just the front-end!

**Comment by martinheidegger** [comment]
Thats why I wrote 50% ;)

**Pull request merged**
