### PR TITLE
Added Atlanta chapter.

### PR DESCRIPTION
**Pull request by airportyh**

### CODE REVIEW

**Comment by watson** [comment]
@maxogden I was about to merge this PR, but noticed that the comitter was himself an repo owner. I then looked at a few of the previous chapter pull requests and they were also created by repo owners and all was merged by the person who created the PR on the same day without any comments.

Is this intentional and to give the other owners a chance to have a say? We might have talked about this before, so I'm sorry if I forgot about it... just curious about the workflow :)

**Comment by martinheidegger** [comment]
https://github.com/nodeschool/organizers/issues/28

**Comment by watson** [comment]
@martinheidegger thanks :) The step regarding the PR is:
https://github.com/nodeschool/organizers/blob/master/README.md#5

It doesn't actually state that new owners should close it them self or not, so I guess they can do that or that any other owner can as well right?

**Comment by martinheidegger** [comment]
@watson I strongly wish for a bigger involvement of the chapter leaders into the project. Merging their own requests is fine by me but I think it would be great if other owners would start to take more charge.

**Comment by watson** [comment]
@martinheidegger I'll go ahead and merge this one then :)

**Comment by airportyh** [comment]
Thanks! I realized I could do it, but didn't know if it required a manual step to deploy the site in addition.

**Comment by watson** [comment]
@airportyh everything that is merged to master is deployed automatically right away

**Pull request merged**
