### PR TITLE
sort events chronologically

### PR DESCRIPTION
**Pull request by Trott**
Current event list is reverse chronological sorting which is (to me, at least) confusing. I expect the next event to be the first one listed, not the last one listed. This change reverses that sorting for a hopefully more intuitive listing.

### CODE REVIEW

**Comment by martinheidegger** [comment]
I think this has side effects on the map. https://github.com/nodeschool/nodeschool.github.io/blob/8577a26fa59470bbfd4a09dcb9800768a333fa7b/js/main.js#L129 This method assumes that the newest one is atop.

**Comment by Trott** [comment]
Whoops, I should have caught that! Fixed now.

**Comment by Trott** [comment]
Anything I can do to move this forward?

**Comment by sudodoki** [comment]
LGTM :+1: if noone says anything going to merge tomorrow evening

**Pull request merged**
