### PR TITLE
[WIP] Add Arabic Translation

### PR DESCRIPTION
**Pull request by martinheidegger**
Created PR from the arabic translation done in https://github.com/nodeschool/discussions/issues/748

- [x] Menu
- [x] Index
- [ ] About
- [ ] Header
- [ ] Footer
- [ ] Events
- [ ] Chapters
- [ ] Host
- [ ] Workshopper

### CODE REVIEW

**Comment by watson** [comment]
@martinheidegger Can you please rebase against master? It cannot be merged as is

**Comment by martinheidegger** [comment]
The PR was a result of cleaning some old threads in the discussions list. I was hoping someone else could attend to it, maybe @Azzurrio ?

**Comment by Azzurrio** [comment]
@watson Done!

**Comment by watson** [comment]
@Azzurrio @martinheidegger Nice work :) I notice that not all keys have been translated... is this on purpose?

**Comment by martinheidegger** [comment]
@watson the title of the PR says "first 3 sections" :smile:

**Comment by Azzurrio** [comment]
@watson Yeah, We are still working on it to translate all keys. Also we want to use RTL style with Arabic content so everything can be consistent. I hope we can find more suggestions & contributions.

**Comment by watson** [comment]
@martinheidegger Ah, I should learn to read the full title ;)

So is the general feeling here that adding a partly translated json file hopefully will get people to contribute with the missing parts? In that case we should just get this deployed right away, or was this PR just meant as a WIP around which we could finish the translation before deploying? I'm sorry if you guys already had this discussion and that I'm just asking stupid questions - I don't want to hold anything back.

**Comment by martinheidegger** [comment]
@watson It is my impression that a little information is better than none. 

@Azzurrio Do you want to finish the whole site now or do you want to publish this part first?

**Comment by conrado** [comment]
It is good that people can start doing code-review, I wouldn't publish half-translated content on a site because it looks half-baked.

**Comment by Azzurrio** [comment]
@conrado I agree +1
@watson & @martinheidegger I think that at least we've to translate all keys into Arabic before publishing it. Then in regards to RTL style we can do it in another version of publishing.

**Comment by martinheidegger** [comment]
@Azzurrio I updated the PR description.

**Comment by watson** [comment]
@Azzurrio good compromize :)

**Comment by Azzurrio** [comment]
@martinheidegger Perfect :+1:

**Comment by Azzurrio** [comment]
@ahmadajmi Please update the list in the description with the sections you've done

**Pull request closed without merging**
