### PR TITLE
Add learnyouhtml as core workshopper

### PR DESCRIPTION
**Pull request by denysdovhan**
Just adding my new workshopper: [`learnyouhtml`](https://github.com/denysdovhan/learnyouhtml)

Will be glad to move this to the workshopper org.

### CODE REVIEW

**Comment by jpwesselink** [comment]
Let me give this a try tomorrow. Anyone else tried it? I

**Comment by denysdovhan** [comment]
@jpwesselink we've had a NodeSchool Chernivtsi with this workshopper last Saturday 😉

**Comment by jpwesselink** [comment]
We gonna try it tonight in Amsterdam :D

**Comment by fforres** [comment]
Looks awesome, 
I'll try this tonight 👍

**Comment by denysdovhan** [comment]
@jpwesselink @fforres cool! Feel free to send a PR with fixes or improvements.

**Comment by denysdovhan** [comment]
@jpwesselink can I merge?

**Comment by jpwesselink** [comment]
Definitely!

**Pull request merged**
